export const CALL_API = Symbol('Call API')

export const GET_SNIPPET_REQUEST = "API_GET_SNIPPET_REQUEST"
export const GET_SNIPPET_SUCCESS = "API_GET_SNIPPET_SUCCESS"
export const GET_SNIPPET_FAILURE = "API_GET_SNIPPET_FAILURE"

export const ADD_SNIPPET_REQUEST = "API_ADD_SNIPPET_REQUEST"
export const ADD_SNIPPET_SUCCESS = "API_ADD_SNIPPET_SUCCESS"
export const ADD_SNIPPET_FAILURE = "API_ADD_SNIPPET_FAILURE"

export const SHOW_ADD_SNIPPET_FORM = "SHOW_ADD_SNIPPET_FORM"
export const HIDE_ADD_SNIPPET_FORM = "HIDE_ADD_SNIPPET_FORM"

export const RETRIEVE_SNIPPETS = "RETRIEVE_SNIPPETS"

export const ADD_NEW_SNIPPET = "ADD_NEW_SNIPPET"

export const ADD_NEW_TAG = "ADD_NEW_TAG"
