const ActionTypes = {
  SHOW_ADD_SNIPPET_FORM: "SHOW_ADD_SNIPPET_FORM",
  HIDE_ADD_SNIPPET_FORM: "HIDE_ADD_SNIPPET_FORM",
  ADD_NEW_SNIPPET: "ADD_NEW_SNIPPET",
  ADD_NEW_TAG: "ADD_NEW_TAG",
  RETRIEVE_SNIPPETS: "RETRIEVE_SNIPPETS",
}

export default ActionTypes
