export const CALL_API = Symbol('Call API')

export const ADD_NEW_SNIPPET       = "ADD_NEW_SNIPPET"
export const RETRIEVE_SNIPPETS     = "RETRIEVE_SNIPPETS"
export const GET_SNIPPET_REQUEST   = "API_GET_SNIPPET_REQUEST"
export const GET_SNIPPET_SUCCESS   = "API_GET_SNIPPET_SUCCESS"
export const GET_SNIPPET_FAILURE   = "API_GET_SNIPPET_FAILURE"
export const ADD_SNIPPET_REQUEST   = "API_ADD_SNIPPET_REQUEST"
export const ADD_SNIPPET_SUCCESS   = "API_ADD_SNIPPET_SUCCESS"
export const ADD_SNIPPET_FAILURE   = "API_ADD_SNIPPET_FAILURE"
export const SHOW_ADD_SNIPPET_FORM = "SHOW_ADD_SNIPPET_FORM"
export const HIDE_ADD_SNIPPET_FORM = "HIDE_ADD_SNIPPET_FORM"

export const ADD_NEW_TAG       = "ADD_NEW_TAG"
export const RETRIEVE_TAGS     = "RETRIEVE_TAGS"
export const ADD_TAG_REQUEST   = "API_ADD_TAG_REQUEST"
export const ADD_TAG_SUCCESS   = "API_ADD_TAG_SUCCESS"
export const ADD_TAG_FAILURE   = "API_ADD_TAG_FAILURE"
export const GET_TAG_REQUEST   = "API_GET_TAG_REQUEST"
export const GET_TAG_SUCCESS   = "API_GET_TAG_SUCCESS"
export const GET_TAG_FAILURE   = "API_GET_TAG_FAILURE"
export const SHOW_ADD_TAG_FORM = "SHOW_ADD_TAG_FORM"
export const HIDE_ADD_TAG_FORM = "HIDE_ADD_TAG_FORM"

export const FILTER_BY_TAG_ID       = "FILTER_BY_TAG_ID"
export const REMOVE_ALL_TAG_FILTERS = "REMOVE_ALL_TAG_FILTERS"
export const FILTER_SNIPPET_REQUEST = "FILTER_SNIPPET_REQUEST"
export const FILTER_SNIPPET_SUCCESS = "FILTER_SNIPPET_SUCCESS"
export const FILTER_SNIPPET_FAILURE = "FILER_SNIPPET_FAILURE"
export const UPDATE_SELECTED_TAG    = "UPDATE_SELECTED_TAG"

export const ADD_TAG_TO_NEW_SNIPPET      = "ADD_TAG_TO_NEW_SNIPPET"
export const REMOVE_TAG_FROM_NEW_SNIPPET = "REMOVE_TAG_FROM_NEW_SNIPPET"

export const REMOVE_SNIPPET = "REMOVE_SNIPPET"
export const REMOVE_SNIPPET_REQUEST = "REMOVE_SNIPPET_REQUEST"
export const REMOVE_SNIPPET_SUCCESS = "REMOVE_SNIPPET_SUCCESS"
export const REMOVE_SNIPPET_FAILURE = "REMOVE_SNIPPET_FAILURE"

export const LOCK_SNIPPET   = "LOCK_SNIPPET"
export const UNLOCK_SNIPPET = "UNLOCK_SNIPPET"

export const LOCK_SNIPPET_REQUEST = "LOCK_SNIPPET_REQUEST"
export const LOCK_SNIPPET_SUCCESS = "LOCK_SNIPPET_SUCCESS"
export const LOCK_SNIPPET_FAILURE = "LOCK_SNIPPET_FAILURE"

export const REMOVE_FLASH_MESSAGE = "REMOVE_FLASH_MESSAGE"

export const RETRIEVE_BOARDS = "RETRIEVE_BOARDS"
export const GET_BOARDS_REQUEST = "GET_BOARDS_REQUEST"
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS"
export const GET_BOARDS_FAILURE = "GET_BOARDS_FAILURE"

export const SELECT_BOARD = "SELECT_BOARD"

export const SHOW_BOARD_LIST = "SHOW_BOARD_LIST"

export const SHOW_NEW_BOARD_FORM = "SHOW_NEW_BOARD_FORM"
export const HIDE_NEW_BOARD_FORM = "HIDE_NEW_BOARD_FORM"

export const CREATE_BOARD = "CREATE_BOARD"
export const CREATE_BOARD_REQUEST = "CREATE_BOARDS_REQUEST"
export const CREATE_BOARD_SUCCESS = "CREATE_BOARDS_SUCCESS"
export const CREATE_BOARD_FAILURE = "CREATE_BOARDS_FAILURE"

export const SET_SLUG   = "SET_SLUG"
export const CLEAR_SLUG = "CLEAR_SLUG"
export const DISPLAY_SLUG = "DISPLAY_SLUG"
export const RETRIEVE_SLUG = "RETRIEVE_SLUG"

export const DISPLAY_SLUG_REQUEST = "DISPLAY_SLUG_REQUEST"
export const DISPLAY_SLUG_SUCCESS = "DISPLAY_SLUG_SUCCESS"
export const DISPLAY_SLUG_FAILURE = "DISPLAY_SLUG_FAILURE"
