export const CALL_API = Symbol('Call API')

export const GET_SNIPPET_REQUEST = "API_GET_SNIPPET_REQUEST"
export const GET_SNIPPET_SUCCESS = "API_GET_SNIPPET_SUCCESS"
export const GET_SNIPPET_FAILURE = "API_GET_SNIPPET_FAILURE"

export const ADD_SNIPPET_REQUEST = "API_ADD_SNIPPET_REQUEST"
export const ADD_SNIPPET_SUCCESS = "API_ADD_SNIPPET_SUCCESS"
export const ADD_SNIPPET_FAILURE = "API_ADD_SNIPPET_FAILURE"
